print branch name

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -19,35 +19,34 @@ jobs:
       - name: Set Environment Variables
         run: |
           echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
-          
           echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
-          echo "this is PR - $PR_NUMBER"
+          echo "Current branch: ${GITHUB_REF#refs/heads/}"
 
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      # - name: Log in to Docker Hub
+      #   uses: docker/login-action@v3
+      #   with:
+      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
+      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build and Push Docker Image
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          file: Dockerfile
-          push: true
-          tags: bhatiasunny/my-preview-app:${{ env.SHORT_SHA }}
+      # - name: Build and Push Docker Image
+      #   uses: docker/build-push-action@v5
+      #   with:
+      #     context: .
+      #     file: Dockerfile
+      #     push: true
+      #     tags: bhatiasunny/my-preview-app:${{ env.SHORT_SHA }}
 
-      - name: Checkout and Update Kustomization File
-        run: |
-          cd kustomize-preview-app
-          if [ -f "kustomization.yaml" ]; then
-            echo "✅ Found kustomization.yaml, updating..."
-            sed -i "s|newTag:.*|newTag: ${SHORT_SHA}|" kustomization.yaml
-          else
-            echo "❌ ERROR: kustomization.yaml not found!"
-            exit 1
-          fi
-          git config --global user.name "github-actions"
-          git config --global user.email "github-actions@github.com"
-          git commit -am "Update image tag to ${SHORT_SHA} for PR-${PR_NUMBER}"
-          git push
+      # - name: Checkout and Update Kustomization File
+      #   run: |
+      #     cd kustomize-preview-app
+      #     if [ -f "kustomization.yaml" ]; then
+      #       echo "✅ Found kustomization.yaml, updating..."
+      #       sed -i "s|newTag:.*|newTag: ${SHORT_SHA}|" kustomization.yaml
+      #     else
+      #       echo "❌ ERROR: kustomization.yaml not found!"
+      #       exit 1
+      #     fi
+      #     git config --global user.name "github-actions"
+      #     git config --global user.email "github-actions@github.com"
+      #     git commit -am "Update image tag to ${SHORT_SHA} for PR-${PR_NUMBER}"
+      #     git push 
